version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  prettierd: &prettierd
    format-command: prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} ${--tab-width=tabSize} ${--use-tabs=!insertSpaces}
    format-stdin: true

  javascript-prettier: &javascript-prettier
    format-command: "prettierd ${INPUT}"
    format-stdin: true

languages:
  typescript:
    - <<: *javascript-prettier
  javascript:
    - <<: *javascript-prettier
  yaml:
    - <<: *prettierd
