version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  javascript-prettier: &javascript-prettier
    format-command: 'prettierd ${INPUT}'
    format-stdin: true

languages:
  typescript:
    - <<: *javascript-prettier
  javascript:
    - <<: *javascript-prettier
