version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  javascript-prettier: &javascript-prettier
    format-command: './node_modules/.bin/prettier ${INPUT}'

languages:
  typescript:
    - <<: *javascript-prettier
  javascript:
    - <<: *javascript-prettier
