version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  prettierd-yaml: &prettierd-yaml
    format-command: prettierd ${INPUT} --parser yaml ${--range-start=charStart} ${--range-end=charEnd} ${--tab-width=tabSize} ${--use-tabs=!insertSpaces}
    format-stdin: true

  prettierd-json: &prettierd-json
    format-command: "prettierd ${INPUT} --parser json ${--range-start=charStart} ${--range-end=charEnd} ${--tab-width=tabSize} ${--use-tabs=!insertSpaces}"
    format-stdin: true

  javascript-prettier: &javascript-prettier
    format-command: "prettierd ${INPUT}"
    format-stdin: true

languages:
  typescript:
    - <<: *javascript-prettier
  javascript:
    - <<: *javascript-prettier
  yaml:
    - <<: *prettierd-yaml
  json:
    - <<: *prettierd-json
