
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/rose-pine/dist/rose-pine-moon.toml"]
